### ISSUE TITLE
Wiki Feedback

### ISSUE THREAD

**Issue by edherm** [babypwant/week12-day-1#2]
Hello! 

I am reviewing all group wikis today and wanted to drop a thing here that I would like y'all to take care of.

## Schema
- [ ] How are you going to look up a user's lists if that list is empty of tasks?

Once these are taken care of, please drop your responses/updates here as a response to this issue.

Thanks, y'all!!
Ed

**Comment by akuemperSFDC** [comment]
We changed our database schema slightly.  Instead of having a one-to-many relationship between users and tasks, we are creating a one-to-many relationship between users and lists, and then a one-to-many relationship between a list and tasks.  We have updated our database schema picture/wiki and database to reflect this change.
